package com.aigallery.rewrite.domain.model

/**
 * AI Model domain model
 */
data class AIModel(
    val id: String,
    val name: String,
    val description: String,
    val provider: ModelProvider,
    val size: String,
    val sizeBytes: Long,
    val quantization: String,
    val parameters: String,
    val downloadUrl: String,
    val mirrorUrl: String,
    val hash: String?,
    val isMultimodal: Boolean,
    val minMemory: Long,
    val status: ModelStatus = ModelStatus.NOT_DOWNLOADED,
    val downloadProgress: Float = 0f,
    val isMnnModel: Boolean = false  // MNN 模型为目录结构
)

enum class ModelProvider(val displayName: String, val mirrorName: String) {
    HUGGING_FACE("HuggingFace", "ModelScope"),
    MODELSCOPE("ModelScope", "ModelScope"),
    ALI_QWEN("阿里通义千问", "镜像"),
    GOOGLE("Google", "镜像"),
    MISTRAL("Mistral", "镜像"),
    MICROSOFT("Microsoft", "镜像")
}

enum class ModelStatus {
    NOT_DOWNLOADED,
    DOWNLOADING,
    PAUSED,
    DOWNLOADED,
    DOWNLOAD_FAILED,
    INITIALIZING,
    READY,
    FAILED
}

/**
 * Predefined model catalog with MNN optimized models
 * All models use ModelScope as primary source for Chinese users
 * 
 * Note: GGUF models (mistral-7b, phi3-3.8b, gemma2-2b, llama3-8b, qwen2-7b, qwen2.5-7b)
 * have been removed as they do not have MNN format versions available on ModelScope
 */
object ModelCatalog {
    val supportedModels = listOf(
        // ============ Qwen 2.5 系列 MNN 模型 ============
        AIModel(
            id = "qwen2.5-0.5b-mnn",
            name = "Qwen 2.5 0.5B (MNN)",
            description = "MNN优化版，骁龙778G+流畅运行，极低内存占用",
            provider = ModelProvider.MODELSCOPE,
            size = "800MB",
            sizeBytes = 800_000_000,
            quantization = "MNN-INT4",
            parameters = "0.5B",
            downloadUrl = "MNN://Qwen2.5-0.5B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2.5-0.5B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 1_500_000_000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen2.5-1.5b-mnn",
            name = "Qwen 2.5 1.5B (MNN)",
            description = "MNN优化版，中文能力强，推荐骁龙778G+",
            provider = ModelProvider.MODELSCOPE,
            size = "1.6GB",
            sizeBytes = 1_600_000_000,
            quantization = "MNN-INT4",
            parameters = "1.5B",
            downloadUrl = "MNN://Qwen2.5-1.5B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2.5-1.5B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2_500_000_000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen2.5-3b-mnn",
            name = "Qwen 2.5 3B (MNN)",
            description = "MNN优化版，性能均衡，大内存手机推荐",
            provider = ModelProvider.MODELSCOPE,
            size = "2.8GB",
            sizeBytes = 2_800_000_000,
            quantization = "MNN-INT4",
            parameters = "3B",
            downloadUrl = "MNN://Qwen2.5-3B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2.5-3B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 4_500_000_000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen2.5-7b-mnn",
            name = "Qwen 2.5 7B (MNN)",
            description = "MNN优化版，强劲性能，需要8GB以上内存",
            provider = ModelProvider.MODELSCOPE,
            size = "4.2GB",
            sizeBytes = 4_200_000_000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://Qwen2.5-7B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2.5-7B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 6_500_000_000,
            isMnnModel = true
        ),
        
        // ============ Qwen 3.5 系列 MNN 模型 ============
        AIModel(
            id = "qwen3.5-0.8b-mnn",
            name = "Qwen3.5 0.8B (MNN)",
            description = "通义千问3.5最小版，混合注意力架构，超低内存",
            provider = ModelProvider.MODELSCOPE,
            size = "650MB",
            sizeBytes = 650_000_000,
            quantization = "MNN-INT4",
            parameters = "0.8B",
            downloadUrl = "MNN://Qwen3.5-0.8B-MNN",
            mirrorUrl = "MNN://Qwen3.5-0.8B-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 1_200_000_000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3.5-2b-mnn",
            name = "Qwen3.5 2B (MNN)",
            description = "通义千问3.5轻量版，75%线性注意力，省内存",
            provider = ModelProvider.MODELSCOPE,
            size = "1.5GB",
            sizeBytes = 1_500_000_000,
            quantization = "MNN-INT4",
            parameters = "2B",
            downloadUrl = "MNN://Qwen3.5-2B-MNN",
            mirrorUrl = "MNN://Qwen3.5-2B-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 2_500_000_000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3.5-4b-mnn",
            name = "Qwen3.5 4B (MNN)",
            description = "通义千问3.5均衡版，混合注意力，最强中文能力",
            provider = ModelProvider.MODELSCOPE,
            size = "2.8GB",
            sizeBytes = 2_800_000_000,
            quantization = "MNN-INT4",
            parameters = "4B",
            downloadUrl = "MNN://Qwen3.5-4B-MNN",
            mirrorUrl = "MNN://Qwen3.5-4B-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 4_500_000_000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3.5-9b-mnn",
            name = "Qwen3.5 9B (MNN)",
            description = "通义千问3.5性能版，高精度，支持256K超长上下文",
            provider = ModelProvider.MODELSCOPE,
            size = "5.2GB",
            sizeBytes = 5_200_000_000,
            quantization = "MNN-INT4",
            parameters = "9B",
            downloadUrl = "MNN://Qwen3.5-9B-MNN",
            mirrorUrl = "MNN://Qwen3.5-9B-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 8_000_000_000,
            isMnnModel = true
        ),
        
        // ============ Qwen2-VL 多模态系列 MNN ============
        AIModel(
            id = "qwen2-vl-2b-mnn",
            name = "Qwen2-VL 2B (MNN)",
            description = "Qwen2视觉版，支持图片理解，骁龙8系推荐",
            provider = ModelProvider.MODELSCOPE,
            size = "2.2GB",
            sizeBytes = 2_200_000_000,
            quantization = "MNN-INT4",
            parameters = "2B",
            downloadUrl = "MNN://Qwen2-VL-2B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2-VL-2B-Instruct-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 3_500_000_000,
            isMnnModel = true
        ),
        
        // ============ Qwen2.5-Omni 多模态系列 MNN ============
        AIModel(
            id = "qwen2.5-omni-3b-mnn",
            name = "Qwen2.5-Omni 3B (MNN)",
            description = "Qwen2.5全模态版，支持语音+视觉+文本",
            provider = ModelProvider.MODELSCOPE,
            size = "3.0GB",
            sizeBytes = 3_000_000_000,
            quantization = "MNN-INT4",
            parameters = "3B",
            downloadUrl = "MNN://Qwen2.5-Omni-3B-MNN",
            mirrorUrl = "MNN://Qwen2.5-Omni-3B-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 5_000_000_000,
            isMnnModel = true
        ),

        // ============ Qwen 系列其他模型 ============
        AIModel(
            id = "qwen-7b-chat-mnn",
            name = "Qwen 7B Chat (MNN)",
            description = "Qwen初代聊天模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://Qwen-7B-Chat-MNN",
            mirrorUrl = "MNN://Qwen-7B-Chat-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen2-7b-instruct-mnn",
            name = "Qwen2 7B Instruct (MNN)",
            description = "Qwen2系列，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://Qwen2-7B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2-7B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen2.5-coder-1.5b-instruct-mnn",
            name = "Qwen2.5-Coder 1.5B (MNN)",
            description = "Qwen2.5代码模型，1.5B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.8GB",
            sizeBytes = 1800000000,
            quantization = "MNN-INT4",
            parameters = "1.5B",
            downloadUrl = "MNN://Qwen2.5-Coder-1.5B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2.5-Coder-1.5B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 3000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen2.5-coder-7b-instruct-mnn",
            name = "Qwen2.5-Coder 7B (MNN)",
            description = "Qwen2.5代码模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://Qwen2.5-Coder-7B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2.5-Coder-7B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen2.5-math-7b-instruct-mnn",
            name = "Qwen2.5-Math 7B (MNN)",
            description = "Qwen2.5数学模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://Qwen2.5-Math-7B-Instruct-MNN",
            mirrorUrl = "MNN://Qwen2.5-Math-7B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3-0.6b-mnn",
            name = "Qwen3 0.6B (MNN)",
            description = "Qwen3小型，0.6B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "700MB",
            sizeBytes = 700000000,
            quantization = "MNN-INT4",
            parameters = "0.6B",
            downloadUrl = "MNN://Qwen3-0.6B-MNN",
            mirrorUrl = "MNN://Qwen3-0.6B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 1200000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3-1.7b-mnn",
            name = "Qwen3 1.7B (MNN)",
            description = "Qwen3小型，1.7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.8GB",
            sizeBytes = 1800000000,
            quantization = "MNN-INT4",
            parameters = "1.7B",
            downloadUrl = "MNN://Qwen3-1.7B-MNN",
            mirrorUrl = "MNN://Qwen3-1.7B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 3000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3-4b-mnn",
            name = "Qwen3 4B (MNN)",
            description = "Qwen3主流，4B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "2.8GB",
            sizeBytes = 2800000000,
            quantization = "MNN-INT4",
            parameters = "4B",
            downloadUrl = "MNN://Qwen3-4B-MNN",
            mirrorUrl = "MNN://Qwen3-4B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 4500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3-8b-mnn",
            name = "Qwen3 8B (MNN)",
            description = "Qwen3大型，8B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "5.2GB",
            sizeBytes = 5200000000,
            quantization = "MNN-INT4",
            parameters = "8B",
            downloadUrl = "MNN://Qwen3-8B-MNN",
            mirrorUrl = "MNN://Qwen3-8B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 8000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3-14b-mnn",
            name = "Qwen3 14B (MNN)",
            description = "Qwen3大型，14B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "8.5GB",
            sizeBytes = 8500000000,
            quantization = "MNN-INT4",
            parameters = "14B",
            downloadUrl = "MNN://Qwen3-14B-MNN",
            mirrorUrl = "MNN://Qwen3-14B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 12000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3-32b-mnn",
            name = "Qwen3 32B (MNN)",
            description = "Qwen3超大型，32B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "18GB",
            sizeBytes = 18000000000,
            quantization = "MNN-INT4",
            parameters = "32B",
            downloadUrl = "MNN://Qwen3-32B-MNN",
            mirrorUrl = "MNN://Qwen3-32B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 24000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3.6-27b-mnn",
            name = "Qwen3.6 27B (MNN)",
            description = "Qwen3.6最新发布，27B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "15GB",
            sizeBytes = 15000000000,
            quantization = "MNN-INT4",
            parameters = "27B",
            downloadUrl = "MNN://Qwen3.6-27B-MNN",
            mirrorUrl = "MNN://Qwen3.6-27B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 20000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3.6-35b-a3b-mnn",
            name = "Qwen3.6 35B A3B (MNN)",
            description = "Qwen3.6 MoE架构，35B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "20GB",
            sizeBytes = 20000000000,
            quantization = "MNN-INT4",
            parameters = "35B MoE",
            downloadUrl = "MNN://Qwen3.6-35B-A3B-MNN",
            mirrorUrl = "MNN://Qwen3.6-35B-A3B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 26000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwq-32b-mnn",
            name = "QwQ-32B (MNN)",
            description = "Qwen推理模型，32B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "18GB",
            sizeBytes = 18000000000,
            quantization = "MNN-INT4",
            parameters = "32B",
            downloadUrl = "MNN://QwQ-32B-MNN",
            mirrorUrl = "MNN://QwQ-32B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 24000000000,
            isMnnModel = true
        ),

        // ============ Qwen3.5 Claude蒸馏系列 ============
        AIModel(
            id = "qwen3.5-0.8b-claude-reasoning-mnn",
            name = "Qwen3.5 0.8B Claude Reasoning (MNN)",
            description = "Claude蒸馏推理模型，0.8B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "850MB",
            sizeBytes = 850000000,
            quantization = "MNN-INT4",
            parameters = "0.8B",
            downloadUrl = "MNN://Qwen3.5-0.8B-Claude-4.6-Opus-Reasoning-Distilled-MNN",
            mirrorUrl = "MNN://Qwen3.5-0.8B-Claude-4.6-Opus-Reasoning-Distilled-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 1500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3.5-2b-claude-reasoning-mnn",
            name = "Qwen3.5 2B Claude Reasoning (MNN)",
            description = "Claude蒸馏推理模型，2B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.8GB",
            sizeBytes = 1800000000,
            quantization = "MNN-INT4",
            parameters = "2B",
            downloadUrl = "MNN://Qwen3.5-2B-Claude-4.6-Opus-Reasoning-Distilled-MNN",
            mirrorUrl = "MNN://Qwen3.5-2B-Claude-4.6-Opus-Reasoning-Distilled-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 3000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3.5-4b-claude-reasoning-mnn",
            name = "Qwen3.5 4B Claude Reasoning (MNN)",
            description = "Claude蒸馏推理模型，4B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "2.8GB",
            sizeBytes = 2800000000,
            quantization = "MNN-INT4",
            parameters = "4B",
            downloadUrl = "MNN://Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-MNN",
            mirrorUrl = "MNN://Qwen3.5-4B-Claude-4.6-Opus-Reasoning-Distilled-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 4500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "qwen3.5-27b-claude-reasoning-mnn",
            name = "Qwen3.5 27B Claude Reasoning (MNN)",
            description = "Claude蒸馏推理模型，27B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "15GB",
            sizeBytes = 15000000000,
            quantization = "MNN-INT4",
            parameters = "27B",
            downloadUrl = "MNN://Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled-MNN",
            mirrorUrl = "MNN://Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 20000000000,
            isMnnModel = true
        ),

        // ============ DeepSeek系列 ============
        AIModel(
            id = "deepseek-r1-1.5b-qwen-mnn",
            name = "DeepSeek R1 1.5B Qwen (MNN)",
            description = "DeepSeek蒸馏推理模型，1.5B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.6GB",
            sizeBytes = 1600000000,
            quantization = "MNN-INT4",
            parameters = "1.5B",
            downloadUrl = "MNN://DeepSeek-R1-1.5B-Qwen-MNN",
            mirrorUrl = "MNN://DeepSeek-R1-1.5B-Qwen-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "deepseek-r1-7b-qwen-mnn",
            name = "DeepSeek R1 7B Qwen (MNN)",
            description = "DeepSeek蒸馏推理模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://DeepSeek-R1-7B-Qwen-MNN",
            mirrorUrl = "MNN://DeepSeek-R1-7B-Qwen-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "deepseek-llm-7b-chat-mnn",
            name = "DeepSeek LLM 7B Chat (MNN)",
            description = "DeepSeek初代聊天模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://deepseek-llm-7b-chat-MNN",
            mirrorUrl = "MNN://deepseek-llm-7b-chat-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),

        // ============ LLaMA系列 ============
        AIModel(
            id = "tinyllama-1.1b-chat-mnn",
            name = "TinyLlama 1.1B Chat (MNN)",
            description = "轻量LLM模型，1.1B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.2GB",
            sizeBytes = 1200000000,
            quantization = "MNN-INT4",
            parameters = "1.1B",
            downloadUrl = "MNN://TinyLlama-1.1B-Chat-MNN",
            mirrorUrl = "MNN://TinyLlama-1.1B-Chat-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "tinyllama-1.1b-chat-v1.0-mnn",
            name = "TinyLlama 1.1B Chat v1.0 (MNN)",
            description = "轻量LLM模型v1.0，1.1B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.2GB",
            sizeBytes = 1200000000,
            quantization = "MNN-INT4",
            parameters = "1.1B",
            downloadUrl = "MNN://TinyLlama-1.1B-Chat-v1.0-MNN",
            mirrorUrl = "MNN://TinyLlama-1.1B-Chat-v1.0-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "llama-2-7b-chat-ms-mnn",
            name = "Llama 2 7B Chat MS (MNN)",
            description = "LLaMA2聊天模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://Llama-2-7b-chat-ms-MNN",
            mirrorUrl = "MNN://Llama-2-7b-chat-ms-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "llama-3.2-1b-instruct-mnn",
            name = "Llama 3.2 1B Instruct (MNN)",
            description = "LLaMA3.2指令模型，1B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.2GB",
            sizeBytes = 1200000000,
            quantization = "MNN-INT4",
            parameters = "1B",
            downloadUrl = "MNN://Llama-3.2-1B-Instruct-MNN",
            mirrorUrl = "MNN://Llama-3.2-1B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "llama-3.2-3b-instruct-mnn",
            name = "Llama 3.2 3B Instruct (MNN)",
            description = "LLaMA3.2指令模型，3B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "2.8GB",
            sizeBytes = 2800000000,
            quantization = "MNN-INT4",
            parameters = "3B",
            downloadUrl = "MNN://Llama-3.2-3B-Instruct-MNN",
            mirrorUrl = "MNN://Llama-3.2-3B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 4500000000,
            isMnnModel = true
        ),

        // ============ Gemma系列 ============
        AIModel(
            id = "gemma-2b-it-mnn",
            name = "Gemma 2B Instruct (MNN)",
            description = "Google Gemma指令模型，2B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.8GB",
            sizeBytes = 1800000000,
            quantization = "MNN-INT4",
            parameters = "2B",
            downloadUrl = "MNN://gemma-2b-it-MNN",
            mirrorUrl = "MNN://gemma-2b-it-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 3000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "gemma-7b-it-mnn",
            name = "Gemma 7B Instruct (MNN)",
            description = "Google Gemma指令模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://gemma-7b-it-MNN",
            mirrorUrl = "MNN://gemma-7b-it-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "gemma3-1b-mnn",
            name = "Gemma3 1B (MNN)",
            description = "Google Gemma3，1B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.2GB",
            sizeBytes = 1200000000,
            quantization = "MNN-INT4",
            parameters = "1B",
            downloadUrl = "MNN://Gemma3-1B-MNN",
            mirrorUrl = "MNN://Gemma3-1B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "gemma3-4b-mnn",
            name = "Gemma3 4B (MNN)",
            description = "Google Gemma3，4B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "2.8GB",
            sizeBytes = 2800000000,
            quantization = "MNN-INT4",
            parameters = "4B",
            downloadUrl = "MNN://Gemma3-4B-MNN",
            mirrorUrl = "MNN://Gemma3-4B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 4500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "gemma3-12b-mnn",
            name = "Gemma3 12B (MNN)",
            description = "Google Gemma3，12B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "7.5GB",
            sizeBytes = 7500000000,
            quantization = "MNN-INT4",
            parameters = "12B",
            downloadUrl = "MNN://Gemma3-12B-MNN",
            mirrorUrl = "MNN://Gemma3-12B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 10000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "gemma3-27b-mnn",
            name = "Gemma3 27B (MNN)",
            description = "Google Gemma3，27B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "15GB",
            sizeBytes = 15000000000,
            quantization = "MNN-INT4",
            parameters = "27B",
            downloadUrl = "MNN://Gemma3-27B-MNN",
            mirrorUrl = "MNN://Gemma3-27B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 20000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "gemma3-31b-moe-mnn",
            name = "Gemma3 31B MoE (MNN)",
            description = "Google Gemma3 MoE架构，31B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "18GB",
            sizeBytes = 18000000000,
            quantization = "MNN-INT4",
            parameters = "31B MoE",
            downloadUrl = "MNN://Gemma3-31B-MoE-MNN",
            mirrorUrl = "MNN://Gemma3-31B-MoE-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 24000000000,
            isMnnModel = true
        ),

        // ============ MobileLLM系列 ============
        AIModel(
            id = "mobilellm-125m-mnn",
            name = "MobileLLM 125M (MNN)",
            description = "Meta移动端优化模型，125M参数",
            provider = ModelProvider.MODELSCOPE,
            size = "150MB",
            sizeBytes = 150000000,
            quantization = "MNN-INT4",
            parameters = "125M",
            downloadUrl = "MNN://MobileLLM-125M-MNN",
            mirrorUrl = "MNN://MobileLLM-125M-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "mobilellm-350m-mnn",
            name = "MobileLLM 350M (MNN)",
            description = "Meta移动端优化模型，350M参数",
            provider = ModelProvider.MODELSCOPE,
            size = "400MB",
            sizeBytes = 400000000,
            quantization = "MNN-INT4",
            parameters = "350M",
            downloadUrl = "MNN://MobileLLM-350M-MNN",
            mirrorUrl = "MNN://MobileLLM-350M-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 800000000,
            isMnnModel = true
        ),
        AIModel(
            id = "mobilellm-500m-mnn",
            name = "MobileLLM 500M (MNN)",
            description = "Meta移动端优化模型，500M参数",
            provider = ModelProvider.MODELSCOPE,
            size = "550MB",
            sizeBytes = 550000000,
            quantization = "MNN-INT4",
            parameters = "500M",
            downloadUrl = "MNN://MobileLLM-500M-MNN",
            mirrorUrl = "MNN://MobileLLM-500M-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 1000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "mobilellm-1b-mnn",
            name = "MobileLLM 1B (MNN)",
            description = "Meta移动端优化模型，1B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.1GB",
            sizeBytes = 1100000000,
            quantization = "MNN-INT4",
            parameters = "1B",
            downloadUrl = "MNN://MobileLLM-1B-MNN",
            mirrorUrl = "MNN://MobileLLM-1B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "mobilellm-1.5b-mnn",
            name = "MobileLLM 1.5B (MNN)",
            description = "Meta移动端优化模型，1.5B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.5GB",
            sizeBytes = 1500000000,
            quantization = "MNN-INT4",
            parameters = "1.5B",
            downloadUrl = "MNN://MobileLLM-1.5B-MNN",
            mirrorUrl = "MNN://MobileLLM-1.5B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2500000000,
            isMnnModel = true
        ),

        // ============ Phi系列 ============
        AIModel(
            id = "phi-2-mnn",
            name = "Phi-2 (MNN)",
            description = "微软Phi-2模型，2B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.8GB",
            sizeBytes = 1800000000,
            quantization = "MNN-INT4",
            parameters = "2B",
            downloadUrl = "MNN://phi-2-MNN",
            mirrorUrl = "MNN://phi-2-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 3000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "phi-3.5-mini-instruct-mnn",
            name = "Phi-3.5 Mini Instruct (MNN)",
            description = "微软Phi-3.5迷你指令模型",
            provider = ModelProvider.MODELSCOPE,
            size = "2.2GB",
            sizeBytes = 2200000000,
            quantization = "MNN-INT4",
            parameters = "3.8B",
            downloadUrl = "MNN://phi-3.5-mini-instruct-MNN",
            mirrorUrl = "MNN://phi-3.5-mini-instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 3500000000,
            isMnnModel = true
        ),

        // ============ SmolLM2系列 ============
        AIModel(
            id = "smollm2-135m-instruct-mnn",
            name = "SmolLM2 135M Instruct (MNN)",
            description = "小模型，135M参数",
            provider = ModelProvider.MODELSCOPE,
            size = "180MB",
            sizeBytes = 180000000,
            quantization = "MNN-INT4",
            parameters = "135M",
            downloadUrl = "MNN://SmolLM2-135M-Instruct-MNN",
            mirrorUrl = "MNN://SmolLM2-135M-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "smollm2-360m-instruct-mnn",
            name = "SmolLM2 360M Instruct (MNN)",
            description = "小模型，360M参数",
            provider = ModelProvider.MODELSCOPE,
            size = "420MB",
            sizeBytes = 420000000,
            quantization = "MNN-INT4",
            parameters = "360M",
            downloadUrl = "MNN://SmolLM2-360M-Instruct-MNN",
            mirrorUrl = "MNN://SmolLM2-360M-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 800000000,
            isMnnModel = true
        ),
        AIModel(
            id = "smollm2-1.7b-instruct-mnn",
            name = "SmolLM2 1.7B Instruct (MNN)",
            description = "SmolLM2适中版本，1.7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.6GB",
            sizeBytes = 1600000000,
            quantization = "MNN-INT4",
            parameters = "1.7B",
            downloadUrl = "MNN://SmolLM2-1.7B-Instruct-MNN",
            mirrorUrl = "MNN://SmolLM2-1.7B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2500000000,
            isMnnModel = true
        ),

        // ============ OpenELM系列 ============
        AIModel(
            id = "openelm-270m-instruct-mnn",
            name = "OpenELM 270M Instruct (MNN)",
            description = "苹果开源，270M参数",
            provider = ModelProvider.MODELSCOPE,
            size = "320MB",
            sizeBytes = 320000000,
            quantization = "MNN-INT4",
            parameters = "270M",
            downloadUrl = "MNN://OpenELM-270M-Instruct-MNN",
            mirrorUrl = "MNN://OpenELM-270M-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 700000000,
            isMnnModel = true
        ),
        AIModel(
            id = "openelm-1_1b-instruct-mnn",
            name = "OpenELM 1.1B Instruct (MNN)",
            description = "苹果开源，1.1B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.2GB",
            sizeBytes = 1200000000,
            quantization = "MNN-INT4",
            parameters = "1.1B",
            downloadUrl = "MNN://OpenELM-1_1B-Instruct-MNN",
            mirrorUrl = "MNN://OpenELM-1_1B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "openelm-3b-instruct-mnn",
            name = "OpenELM 3B Instruct (MNN)",
            description = "苹果开源，3B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "2.8GB",
            sizeBytes = 2800000000,
            quantization = "MNN-INT4",
            parameters = "3B",
            downloadUrl = "MNN://OpenELM-3B-Instruct-MNN",
            mirrorUrl = "MNN://OpenELM-3B-Instruct-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 4500000000,
            isMnnModel = true
        ),

        // ============ MiMo系列 (小米) ============
        AIModel(
            id = "mimo-7b-base-mnn",
            name = "MiMo 7B Base (MNN)",
            description = "小米开源基座模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://MiMo-7B-Base-MNN",
            mirrorUrl = "MNN://MiMo-7B-Base-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "mimo-7b-sft-mnn",
            name = "MiMo 7B SFT (MNN)",
            description = "小米开源监督微调模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://MiMo-7B-SFT-MNN",
            mirrorUrl = "MNN://MiMo-7B-SFT-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "mimo-7b-rl-mnn",
            name = "MiMo 7B RL (MNN)",
            description = "小米开源强化学习模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://MiMo-7B-RL-MNN",
            mirrorUrl = "MNN://MiMo-7B-RL-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "mimo-7b-rl-zero-mnn",
            name = "MiMo 7B RL-Zero (MNN)",
            description = "小米开源强化学习零基础模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://MiMo-7B-RL-Zero-MNN",
            mirrorUrl = "MNN://MiMo-7B-RL-Zero-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),

        // ============ 其他中文模型 ============
        AIModel(
            id = "baichuan2-7b-chat-mnn",
            name = "Baichuan2 7B Chat (MNN)",
            description = "百川大模型，7B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.5GB",
            sizeBytes = 4500000000,
            quantization = "MNN-INT4",
            parameters = "7B",
            downloadUrl = "MNN://Baichuan2-7B-Chat-MNN",
            mirrorUrl = "MNN://Baichuan2-7B-Chat-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 7000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "yi-6b-chat-mnn",
            name = "Yi 6B Chat (MNN)",
            description = "零一万物，6B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.0GB",
            sizeBytes = 4000000000,
            quantization = "MNN-INT4",
            parameters = "6B",
            downloadUrl = "MNN://Yi-6B-Chat-MNN",
            mirrorUrl = "MNN://Yi-6B-Chat-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 6500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "glm-4-9b-chat-mnn",
            name = "GLM-4 9B Chat (MNN)",
            description = "智谱GLM-4，9B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "5.5GB",
            sizeBytes = 5500000000,
            quantization = "MNN-INT4",
            parameters = "9B",
            downloadUrl = "MNN://glm-4-9b-chat-MNN",
            mirrorUrl = "MNN://glm-4-9b-chat-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 8000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "chatglm3-6b-mnn",
            name = "ChatGLM3 6B (MNN)",
            description = "智谱ChatGLM3，6B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "4.0GB",
            sizeBytes = 4000000000,
            quantization = "MNN-INT4",
            parameters = "6B",
            downloadUrl = "MNN://chatglm3-6b-MNN",
            mirrorUrl = "MNN://chatglm3-6b-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 6500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "reader-lm-0.5b-mnn",
            name = "ReaderLM 0.5B (MNN)",
            description = "阅读模型，0.5B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "600MB",
            sizeBytes = 600000000,
            quantization = "MNN-INT4",
            parameters = "0.5B",
            downloadUrl = "MNN://reader-lm-0.5b-MNN",
            mirrorUrl = "MNN://reader-lm-0.5b-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 1000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "reader-lm-1.5b-mnn",
            name = "ReaderLM 1.5B (MNN)",
            description = "阅读模型，1.5B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.6GB",
            sizeBytes = 1600000000,
            quantization = "MNN-INT4",
            parameters = "1.5B",
            downloadUrl = "MNN://reader-lm-1.5b-MNN",
            mirrorUrl = "MNN://reader-lm-1.5b-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2500000000,
            isMnnModel = true
        ),

        // ============ 其他多模态模型 ============
        AIModel(
            id = "internvl2_5-1b-mnn",
            name = "InternVL2.5 1B (MNN)",
            description = "InternVL视觉语言模型，1B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.5GB",
            sizeBytes = 1500000000,
            quantization = "MNN-INT4",
            parameters = "1B",
            downloadUrl = "MNN://InternVL2_5-1B-MNN",
            mirrorUrl = "MNN://InternVL2_5-1B-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 2500000000,
            isMnnModel = true
        ),

        // ============ LFM系列 (音频/视觉模型) ============
        AIModel(
            id = "lfm2.5-audio-1.5b-mnn",
            name = "LFM2.5 Audio 1.5B (MNN)",
            description = "音频模型，1.5B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.6GB",
            sizeBytes = 1600000000,
            quantization = "MNN-INT4",
            parameters = "1.5B",
            downloadUrl = "MNN://LFM2.5-Audio-1.5B-MNN",
            mirrorUrl = "MNN://LFM2.5-Audio-1.5B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2-vl-3b-mnn",
            name = "LFM2-VL 3B (MNN)",
            description = "LFM视觉模型，3B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "2.8GB",
            sizeBytes = 2800000000,
            quantization = "MNN-INT4",
            parameters = "3B",
            downloadUrl = "MNN://LFM2-VL-3B-MNN",
            mirrorUrl = "MNN://LFM2-VL-3B-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 4500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2-vl-1.6b-mnn",
            name = "LFM2-VL 1.6B (MNN)",
            description = "LFM视觉模型，1.6B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.6GB",
            sizeBytes = 1600000000,
            quantization = "MNN-INT4",
            parameters = "1.6B",
            downloadUrl = "MNN://LFM2-VL-1.6B-MNN",
            mirrorUrl = "MNN://LFM2-VL-1.6B-MNN",
            hash = null,
            isMultimodal = true,
            minMemory = 2500000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2-2.6b-transcript-mnn",
            name = "LFM2 2.6B Transcript (MNN)",
            description = "LFM转录模型，2.6B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "2.4GB",
            sizeBytes = 2400000000,
            quantization = "MNN-INT4",
            parameters = "2.6B",
            downloadUrl = "MNN://LFM2-2.6B-Transcript-MNN",
            mirrorUrl = "MNN://LFM2-2.6B-Transcript-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 4000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2-24b-a2b-mnn",
            name = "LFM2 24B A2B (MNN)",
            description = "LFM MoE架构，24B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "14GB",
            sizeBytes = 14000000000,
            quantization = "MNN-INT4",
            parameters = "24B MoE",
            downloadUrl = "MNN://LFM2-24B-A2B-MNN",
            mirrorUrl = "MNN://LFM2-24B-A2B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 18000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2-8b-a1b-mnn",
            name = "LFM2 8B A1B (MNN)",
            description = "LFM MoE架构，8B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "5.2GB",
            sizeBytes = 5200000000,
            quantization = "MNN-INT4",
            parameters = "8B MoE",
            downloadUrl = "MNN://LFM2-8B-A1B-MNN",
            mirrorUrl = "MNN://LFM2-8B-A1B-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 8000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2-700m-mnn",
            name = "LFM2 700M (MNN)",
            description = "LFM轻量模型，700M参数",
            provider = ModelProvider.MODELSCOPE,
            size = "750MB",
            sizeBytes = 750000000,
            quantization = "MNN-INT4",
            parameters = "700M",
            downloadUrl = "MNN://LFM2-700M-MNN",
            mirrorUrl = "MNN://LFM2-700M-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 1200000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2-350m-mnn",
            name = "LFM2 350M (MNN)",
            description = "LFM轻量模型，350M参数",
            provider = ModelProvider.MODELSCOPE,
            size = "400MB",
            sizeBytes = 400000000,
            quantization = "MNN-INT4",
            parameters = "350M",
            downloadUrl = "MNN://LFM2-350M-MNN",
            mirrorUrl = "MNN://LFM2-350M-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 800000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2.5-1.2b-thinking-mnn",
            name = "LFM2.5 1.2B Thinking (MNN)",
            description = "LFM思考模型，1.2B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.3GB",
            sizeBytes = 1300000000,
            quantization = "MNN-INT4",
            parameters = "1.2B",
            downloadUrl = "MNN://LFM2.5-1.2B-Thinking-MNN",
            mirrorUrl = "MNN://LFM2.5-1.2B-Thinking-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2.5-1.2b-jp-mnn",
            name = "LFM2.5 1.2B JP (MNN)",
            description = "LFM日语模型，1.2B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.3GB",
            sizeBytes = 1300000000,
            quantization = "MNN-INT4",
            parameters = "1.2B",
            downloadUrl = "MNN://LFM2.5-1.2B-JP-MNN",
            mirrorUrl = "MNN://LFM2.5-1.2B-JP-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        ),
        AIModel(
            id = "lfm2.5-1.2b-base-mnn",
            name = "LFM2.5 1.2B Base (MNN)",
            description = "LFM基座模型，1.2B参数",
            provider = ModelProvider.MODELSCOPE,
            size = "1.3GB",
            sizeBytes = 1300000000,
            quantization = "MNN-INT4",
            parameters = "1.2B",
            downloadUrl = "MNN://LFM2.5-1.2B-Base-MNN",
            mirrorUrl = "MNN://LFM2.5-1.2B-Base-MNN",
            hash = null,
            isMultimodal = false,
            minMemory = 2000000000,
            isMnnModel = true
        )
    )

    /**
     * Get model by ID
     */
    fun getModelById(modelId: String): AIModel? {
        return supportedModels.find { it.id == modelId }
    }

    /**
     * Get models by provider
     */
    fun getModelsByProvider(provider: ModelProvider): List<AIModel> {
        return supportedModels.filter { it.provider == provider }
    }

    /**
     * Get MNN models only
     */
    fun getMnnModels(): List<AIModel> {
        return supportedModels.filter { it.isMnnModel }
    }

    /**
     * Get small models suitable for mobile devices
     */
    fun getSmallModels(): List<AIModel> {
        return supportedModels.filter { 
            it.parameters.contains("0.5") || 
            it.parameters.contains("0.8") ||
            it.parameters.contains("1.5") || 
            it.parameters.contains("2") || 
            it.parameters.contains("3") 
        }
    }

    /**
     * Get multimodal models
     */
    fun getMultimodalModels(): List<AIModel> {
        return supportedModels.filter { it.isMultimodal }
    }

    /**
     * Get text-only models
     */
    fun getTextModels(): List<AIModel> {
        return supportedModels.filter { !it.isMultimodal }
    }
}
